### PR TITLE
for #3

### PR DESCRIPTION
**Pull request by m6w6**
Fix issue #3:

* Add json_post.error_response INI entry, specifying whether and which
  response code to send when `json_decode` fails.
* Add json_post.error_exit INI entry, specifying whether to exit PHP
  without running the script when `json_decode` fails.

### CODE REVIEW

**Comment by maxm86545** [comment]
One more test

```
--TEST--
json_post with malformed JSON (https://github.com/m6w6/ext-json_post/issues/3)
--SKIPIF--
<?php
extension_loaded("json_post") or die("skip need json_post support\n");
if (PHP_VERSION_ID < 70000) doe("skip need PHP-7.0+\n");
?>
--INI--
json_post.error_response = 444
json_post.flags = 1
--POST_RAW--
Content-Type: application/json

{
	"greeting": "Hello World
}
--FILE--
<?php
http_response_code(400);
var_dump($_POST);
var_dump(http_response_code());
?>
Done
--EXPECTHEADERS--
Status: 400 Bad Request
X-JSON-Error-Code: 3
--EXPECTF--
array(0) {
}
int(400)
Done
```

**Comment by maxm86545** [comment]
Don't you think the `X-JSON-Error-Code` header is redundant? Logging should be enough.

**Comment by m6w6** [comment]
> Don't you think the `X-JSON-Error-Code` header is redundant? Logging should be enough.

Not sure I can follow. There's nothing logged.

**Comment by maxm86545** [comment]
> There's nothing logged.

Hmm, is it possible to add logging as E_WARNING on encoding error??
https://www.php.net/manual/en/errorfunc.examples.php

**Comment by maxm86545** [comment]
Or set the global constant `JSON_POST_ERROR` with json error code:

Code | Constant | Meaning
-- | -- | -- 
0 | JSON_ERROR_NONE | No error has occurred 
1 | JSON_ERROR_DEPTH | The maximum stack depth has been exceeded
2 | JSON_ERROR_STATE_MISMATCH | Invalid or malformed JSON 
3 | JSON_ERROR_CTRL_CHAR | Control character error, possibly incorrectly encoded 
4 | JSON_ERROR_SYNTAX | Syntax error
5 | JSON_ERROR_UTF8 | Malformed UTF-8 characters, possibly incorrectly encoded 
6 | JSON_ERROR_RECURSION | One or more recursive references in the value to be encoded
7 | JSON_ERROR_INF_OR_NAN | One or more NAN or INF values in the value to be encoded
8 | JSON_ERROR_UNSUPPORTED_TYPE | A value of a type that cannot be encoded was given
9 | JSON_ERROR_INVALID_PROPERTY_NAME | A property name that cannot be encoded was given 
10 | JSON_ERROR_UTF16 | Malformed UTF-16 characters, possibly incorrectly encoded

https://www.php.net/manual/en/function.json-last-error.php


I think `X-JSON-Error-Code` header is unnecessary.

**Review by maxm86545 — APPROVED** [review]
Good job, thank you!

**Comment by maxm86545** [comment]
@m6w6 When will the release be?

**Pull request merged**
